- hosts: all
  become: yes
  tasks:
    - name: stop tomcat
      lineinfile:
        path: /etc/hosts
        line: "169.168.0.1 ansible.xyzcorp.com"
    - name: stop elastic
      package:
        name: elinks
        state: latest
    - name: deploy tomcat.conf
      user:
        name: xyzcorp_audit
        state: present
    - name: deploy elasticsearch.yml
      copy:
        src: /home/ansible/motd
        dest: /etc/motd
    - name: deploy logging.properties for ui2
      copy:
        src: /home/ansible/issue
        dest: /etc/issue
    - name: restart tomcat
      copy:
        src: /home/ansible/issue
        dest: /etc/issue
