- hosts: web
  become: yes
  tasks:
    - name: stop tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: stopped 
    - name: deploy tomcat.conf
      template:
        src: tomcat.conf.j2
        dest: /home/khadijah/tomcat.conf
    - name: restart tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: restarted 
